baseURL = "https://theryss.gq"
defaultContentLanguage = "en"
disqusShortname = "yourdiscussshortname"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en"
paginate = 12
theme = "KeepIt"
title = "ryss.me"
[Permalinks]
posts = "/:year/:filename/"
[author]
name = "theryss"
[blackfriday]
hrefTargetBlank = true
nofollowLinks = true
noreferrerLinks = true
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2
[[menu.main]]
name = "Pages"
url = "/pages/"
weight = 5
[[menu.main]]
name = "About"
url = "/about"
weight = 4
[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 3
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1
[params]
author = "theryss"
avatar = "/images/me/avatar.jpeg"
baidu_verification = ""
bing_verification = ""
cdn_url = ""
description = ""
google_verification = ""
home_mode = ""
keywords = ""
license = "Released under <a rel=\"license external nofollow noopener noreffer\" href=\"https://creativecommons.org/licenses/by-nc/4.0/\" target=\"_blank\">CC BY-NC 4.0</a>"
pinterest_verification = ""
since = 2020
socialShare = false
subtitle = "theryss hugo blog"
yandex_verification = ""
[params.gitalk]
clientId = ""
clientSecret = ""
owner = ""
repo = ""
[params.gitment]
clientId = ""
clientSecret = ""
owner = ""
repo = ""
[params.gravatar]
[params.image]
height = 600
url = "cover.png"
width = 800
[params.logo]
height = 40
url = "logo.png"
width = 127
[params.publisher]
name = "theryss"
[params.publisher.logo]
height = 40
url = "logo.png"
width = 127
[params.share]
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
[params.social]
[params.utterances]
owner = ""
repo = ""
[params.valine]
appId = "your appId"
appKey = "your appKey"
avatar = "mm"
enable = false
language = "en"
notify = false
placeholder = "your comments ..."
verify = false
visitor = true
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
